### ISSUE TITLE
1.1.0 package is invalid

### ISSUE THREAD

**Issue by michaeljohnclancy** [skgmn/StartActivityX#1]
Hi there, am trying to include this repo as a dependency for but it does not seem to be working. I am not 100% certain but does this log (https://jitpack.io/com/github/skgmn/StartActivityX/v1.1.0/build.log) indicate that the build has failed?

Thanks,
Michael

**Comment by michaeljohnclancy** [comment]
For the meantime, I have imported the repo as a local library into my project and its working great!

**Comment by skgmn** [comment]
I'm sorry I just saw this now.
Since 1.2.0, it has been released to maven central so it should work fine.

**Comment by michaeljohnclancy** [comment]
Thank you, all is working well now on both CameraXX and StartActivityX btw!
